version: "3.1"

services:
  backend:
    build: ./backend
    ports:
      - "1234:1234"
    env_file:
      - production.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  bot:
    build: ./bot-controller
    ports:
      - "5000:5000"
